apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ template "name" . }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
